import './globals.css'

export const metadata = {
  title: 'Title',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>hi</h1>
        </nav>
        {children}
      </body>
    </html>
  )
}
